version: "3.8"

services:
  libraryapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/library.db
    volumes:
      - ./data:/app/data

volumes:
  library_data:
